apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: exhort
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: exhort
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: exhort
    app.kubernetes.io/part-of: exhort
  name: exhort
  namespace: exhort
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: exhort
    app.kubernetes.io/instance: exhort
status:
  loadBalancer: {}
